development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: MovieList_development
  pool: 5
  socket: /tmp/mysql.sock
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database:  MovieList_test
  pool: 5
  username:  <%= ENV['DATABASE_USERNAME'] %>
  password:  <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database:  MovieList_production
  pool: 5
  username:  <%= ENV['DATABASE_USERNAME'] %>
  password:  <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
