version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - 8080:3000
    tty: true
    stdin_open: true
    environment:
      TZ: "Asia/Tokyo"
      RAILS_ENV: production

volumes:
  bundle:
    driver: local
